<?php

namespace AppBundle\Repository;

/**
 * AmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmountRepository extends \Doctrine\ORM\EntityRepository
{
}
