<?php

namespace AppBundle\Repository;

/**
 * IngredientAliasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientAliasesRepository extends \Doctrine\ORM\EntityRepository
{
}
