<?php

namespace AppBundle\Repository;

/**
 * IngredientNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientNameRepository extends \Doctrine\ORM\EntityRepository
{
}
