<?php

namespace AppBundle\Repository;

/**
 * InventoryIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
