<?php

namespace AppBundle\Repository;

/**
 * KitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitchenRepository extends \Doctrine\ORM\EntityRepository
{
}
