<?php

namespace AppBundle\Repository;

/**
 * KitchenUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitchenUserRepository extends \Doctrine\ORM\EntityRepository
{
}
