<?php

namespace AppBundle\Repository;

/**
 * KitchenIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitchenIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
