<?php

namespace AppBundle\Repository;

/**
 * RecipeAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeAmountRepository extends \Doctrine\ORM\EntityRepository
{
}
