<?php

namespace AppBundle\Repository;

/**
 * RecipeSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
