<?php

namespace AppBundle\Repository;

/**
 * ShoppinglistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppinglistRepository extends \Doctrine\ORM\EntityRepository
{
}
