<?php

namespace AppBundle\Repository;

/**
 * ShoppinglistIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppinglistIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
