<?php

namespace AppBundle\Repository;

/**
 * UserSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
